---
- name: Install Jenkins agent as a Windows service
  hosts: windows
  gather_facts: false

  collections:
    - ansible.windows
    - community.windows

  roles:
    - role: henryorg.jenkins_windows_agent.windows_jenkins_agent
