namespace: henryorg
name: jenkins_windows_agent
version: 1.0.0
readme: README.md
authors:
  - "Henry Q"
description: "Install and run Jenkins agent as a Windows service (NSSM)."
license: MIT
tags:
  - jenkins
  - windows
  - agent

repository: "https://git.example.com/henryorg/jenkins_windows_agent"
documentation: "https://git.example.com/henryorg/jenkins_windows_agent"
homepage: "https://git.example.com/henryorg/jenkins_windows_agent"
issues: "https://git.example.com/henryorg/jenkins_windows_agent/issues"

dependencies:
  ansible.windows: ">=1.14.0"
  community.windows: ">=1.12.0"

